module.exports =
  [{id : '1',
  task: "e-mail",
  completed: 'false'},
  {id : '2',
  task: "trash",
  completed: 'false'},
  {id : '3',
  task: "dishes",
  completed: 'false'},
  {id : '4',
  task: "bills",
  completed: 'false'},
  {id : '5',
  task: "sort laundry",
  completed: 'true'},
  {id : '6',
  task: "water plants",
  completed: 'true'},
  {id : '7',
  task: "walk dog",
  completed: 'true'},
]
